### ISSUE TITLE
Insufficient description of the plugin in the Moodle Plugins directory

### ISSUE THREAD

**Issue by mudrd8mz** [citizencam/moodle-mod_citizencam#2]
The description does not provide some essential information

* What URLs should be added into the settings
* Information about the integration with the system - is it paid or free? What should admins do to start using the service etc.

**Comment by herbeth1u** [comment]
The complete description has been added to the Plugins directory, including the default URLs you have to put in order to make the plugin work.
Information about pricing has also been added: the plugin is free to use with the official CitizenCam TV.
