### ISSUE TITLE
Attempts to load fonts and fails

### ISSUE THREAD

**Issue by mudrd8mz** [citizencam/moodle-mod_citizencam#4]
In the CSS folder, it tries to load font awesome fonts from URLs like `src:url('../fonts/fontawesome-webfont.eot?v=4.7.0')` which fails.

![image](https://user-images.githubusercontent.com/85831/33478934-5778c0a6-d68b-11e7-96c0-abc4bc4297d4.png)

**Comment by herbeth1u** [comment]
Font Awesome was actually not used, so it was removed in 449542e. spinner.gif has also been added.
